### ISSUE TITLE
Basic implementation for Result and Option

### ISSUE THREAD

**Issue by simplewepro** [simplewepro/rustd#2]
![rustd_hero](https://github.com/simplewepro/rustd/assets/31455686/afbff9f9-f930-4684-8508-fcaeb1bca473)

## Overview

Adding implementations for [Result](https://doc.rust-lang.org/std/result/enum.Result.html) and [Option](https://doc.rust-lang.org/std/option/enum.Option.html), analogue to rust lang ones from rust standart library; links provided.

## Todo items

- [x] add `@rustd/core` documentation

### Features
- [x] create `Result` implementation
- [x] create `Option` implementation

### Unit tests
- [x] `Result.spec` 
- [x] `Option.spec`
